sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ntNP+E0xyPxWvGzkqs53v6Htbc/9F6Ra2WvGoumn25uBAI4vO3rVuRWmmLK8Rx+Y0cZmLk14WLWXsUyyoS2lY33IkJwNS+dRKre4GUcHJzhLrM6wl3ctHMPnjufmxtylozqm0TxQHFcuJ+E2MlaGtRCIHdULxqdk7Hc1PemSVAiFoQbZbNVMb7w7s8BejLLPTN4hT8YY1XKGkaHjEDX0EjgCst6ljx6BEjdD15WCf+szqbC9JkdXrhPVzkR7ng+dEVKPVcOZrL69vAHamW3UvDILdbBTCxtcLdBZ4lCGJ7Vz1oXaShNcDSDB3DUuSlLTvnQD+IT7xYbXfX2iZqjxlWOOuCqxot+Aujcwxk1q2yWV/Recotx/5//1OWhFHlwvfLLqs6E1JFqb0vNYg1JOUYCK3OfkMYBPB9lj1uL/uo+Lpjm0nIZraQCXAxuVkSDy4rFVIr56oYyR4t0olaHCCjQOHaRa2FOGNJK69QR0yMzcG2882z7zgMuioJuwZh/6wI3jYq9I/6LegPjNycj4u/0m1uLC77vTeo/FhK1Y3UXqNhIhUsfIL5XGiOAE9bCMKnQQDCVoej/i/4/WtM+/wIqZSsF17aK0dtepik2u5sxYdxNGnggNDlUFNULrIsrifSj24qQO9LMnF8+ndiC53ugBWwkUOdHOh66sjEcRRdQ=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Tales-and-Novels-of-J-de-La-Fontaine-Volume-16_5290
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy